### PR TITLE
HDEV-269 migrate lp tokens + api integration

### PR DESCRIPTION
**Pull request by schystz**
## Description of Changes

This PR extends https://github.com/HaloDAO/halodao-interface/pull/104 adding the functionality to store pending rewards to an off-chain db (Firebase Firestore).

We've also added a logic to disable "Migrate" button and reset earned xRNBW to 0, for users who already migrated their LP tokens.

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-269)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [x] All files have appropriate file headers and documentation
* [x] I have written new tests for your core changes, as applicable
* [x] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Review by bitcoinbrisbane — APPROVED** [review]

**Review by tracyarciaga — APPROVED** [review]
Code looks good. (wasn't able to test it though)

**Comment by 0xAplki** [comment]
i tried doing a mainnet migration, it went well but it did not add an entry in firestore.

**Comment by 0xAplki** [comment]
From my mainnet test:

0x66456F3aA51D62A0a626cCA8D5347dc83fe9D5a2

https://etherscan.io/tx/0xe9217f74ab0d4167a52d49ed96048061842acd82fbe71832e0bbd588847369a5
https://etherscan.io/tx/0x7edc6ad7256054edfa4d23e8e813ad453fc55785ef5ea31b8ec14535cf7af002
https://etherscan.io/tx/0x359cdcd9926c61f507176dc1fc046fa3192ec8021508faaf5db9010c766468d9

2.28 xRNBW

**Comment by schystz** [comment]
@0xAplki it looks like the API call failed because of a validation issue. The whitelisted pools on our dev env doesn't contain the mainnet pools so API throws a http 400 error. I have added the mainnet pools now and everything works perfectly when I tested using the deployer wallet.

Below is the document created in Firestore:
Screen Shot 2021-10-04 at 9 40 16 AM

**Review by 0xAplki — APPROVED** [review]

**Pull request merged**
