### PR TITLE
Bug fixes/hdb 15 max remove liquidity

### PR DESCRIPTION
**Pull request by schystz**
**IMPORTANT:**
**Please check https://github.com/HaloDAO/halodao-interface/pull/69 first before reviewing this issue, once merged it will make the "Files changed" considerably less**

## Description of Changes

When removing max amount of liquidity, supply BigNumber instead of the computed JS Number amount to avoid precision issue

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-15)

### Developer Checklist:

* [ ] I have followed the guidelines in our Contributing document
* [ ] This PR has a corresponding JIRA ticket
* [ ] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by chris247474** [comment]
This works great @schystz ! https://kovan.etherscan.io/tx/0x73b820e9901402700d698f9dacfe005c5d25e956ef564210431a85df0cdbd5e0

Screen Shot 2021-09-12 at 7 46 34 PM

**Review by chris247474 — APPROVED** [review]
See comment

**Comment by schystz** [comment]
> This works great @schystz ! https://kovan.etherscan.io/tx/0x73b820e9901402700d698f9dacfe005c5d25e956ef564210431a85df0cdbd5e0
> 
> Screen Shot 2021-09-12 at 7 46 34 PM

Reminds me, this needs to be in "long" format so that user sees the full amount (e.g. `1135` instead of `1.1K`). Updated - https://github.com/HaloDAO/halodao-interface/pull/71/commits/2fe77b526e746f6adb07088d2266ceb0429f21d3!

**Review by tracyarciaga — APPROVED** [review]
it is working and code changes looks good.

**Pull request merged**
