### PR TITLE
Features/hdf 152 farm page feedback v2

### PR DESCRIPTION
**Pull request by schystz**
## Description of Changes

- [HDF-153](https://halodao.atlassian.net/browse/HDF-153)  Stake & unstake button is missing the disabled state/color
- [HDF-170](https://halodao.atlassian.net/browse/HDF-170)  Add insufficient balance text under stake & unstake button
- [HDF-169](https://halodao.atlassian.net/browse/HDF-169) UI redesigns
  - website bg color (changed to subtle purple)
  - pool card border color (add purple border)
  - banner color inside pool card (changed to pink)
  - white circular loader for stake button, purple for unstake button

Other changes:

- Updated twitter link to new Twitter handle
- Use 16px font size for pools section/table on web (after result of Slack discussion)
- Added link to "learn about staking" to our gitbook documentation
- Code refactoring
  - moved+refactored `/PositionCard/BalancerPoolCard.tsx` to `/Farm/FarmPoolCard.tsx` (from 1111 to 696 lines of code, 38% decrease)
  - moved `/PoolSummary/index.tsx` to `/Farm/FarmSummary.tsx`
  - rename `usePoolSummary` to `useFarmSummary`

## How To Test

Note: Currently when testing stake & unstake locally with Rewards address `0x38e2851f90c7714f44be3851545C09F58A528d2e`, I get an `gas limit` issue again. But this issue should not hinder from testing the changes from this PR.

### Staking

0. Set your allowance for the BPT contract to 0 using etherscan (so we can test approve)
1. Go to farm page and verify that stake button is disabled
2. Start by entering some amount to stake
    - if amount > BPT balance, you should see the "insufficient balance" text below the stake button
    - else, button should be enabled and title changed to "Approve" (requires step 0, otherwise title will remain "Stake")
2. Tap "Approve" and verify that a white circular loader appears and button becomes disabled
3. After confirming the tx in metamask & getting the confirmation, wait for a few sec and verify that the button becomes enabled and title changed to "Stake"
4. Tap stake and verify that a white circular loader appears and button becomes disabled
5. If either the tx fails or succeed, button should revert back to enabled state, title to "Stake" & stake amount to 0

### Unstaking

1. Go to farm page and verify that unstake button is disabled
2. Start by entering some amount to unstake
    - if amount > staked BPT, you should see the "insufficient balance" text below the unstake button
    - else, button should be enabled and title changed to "Unstake"
2. Tap "Unstake" and verify that a purple circular loader appears and button becomes disabled
3. If either the tx fails or succeed, button should revert back to enabled state, title to "Unstake" & unstake amount to 0

### UI changes

Please refer to the [Figma design](https://www.figma.com/file/lqpLD77mM2olJNrFzuD4Ul/HaloDAO-App?node-id=0%3A1) to compare the Farm page screen on both web and mobile view

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [ ] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

### CODE REVIEW

**Review by ernestpascual — APPROVED** [review]
all works fine with me!

**Review by tracyarciaga — COMMENTED** [review]
@schystz just minor stuff:
1. In Figma, the pool card has a shadow. In our UI, I don't see it.
2. Trying to test approve ->WETH/DAI pool:
a.  Set my approve to 0 on this link:
https://kovan.etherscan.io/address/0x37f80ac90235ce0d3911952d0ce49071a0ffdb1e#writeContract
b. tx successful:
https://kovan.etherscan.io/tx/0x873e55cd9236884d259f870608777e78ed5599d0f95b5da43ad139fd03519335
But I don't  see approve when  I try to input at  stake:

https://user-images.githubusercontent.com/6169194/116845780-68f55300-ac19-11eb-8349-5c64ac00c605.mov

**Comment by tracyarciaga** [comment]
> @schystz just minor stuff:
> 
> 1. In Figma, the pool card has a shadow. In our UI, I don't see it.
> 2. Trying to test approve ->WETH/DAI pool:
>    a.  Set my approve to 0 on this link:
>    https://kovan.etherscan.io/address/0x37f80ac90235ce0d3911952d0ce49071a0ffdb1e#writeContract
>    b. tx successful:
>    https://kovan.etherscan.io/tx/0x873e55cd9236884d259f870608777e78ed5599d0f95b5da43ad139fd03519335
>    But I don't  see approve when  I try to input at  stake:
> 
>  Screen.Recording.2021-05-03.at.14.10.26.mov

@schystz #2 as discussed, is resolved -> my error :)

**Comment by schystz** [comment]
@tracyarciaga added the shadow on the pool card.

Another change I added: made the toast bg color white, so it doesn't blend with the background.
Screen Shot 2021-05-03 at 3 56 48 PM

**Review by tracyarciaga — APPROVED** [review]
Approving this now

**Pull request merged**
