### PR TITLE
Features/hdf 77 harvest rewards

### PR DESCRIPTION
**Pull request by schystz**
## Note

_This PR contains the changes from the following PRs:_

- [PR#6](https://github.com/HaloDAO/halodao-interface/pull/6) Vesting modal
- [PR#7](https://github.com/HaloDAO/halodao-interface/pull/7) DSRT renamed to RNBW

## Description of Changes
- Ensure all HALO balances on halodao-interface are calculated using HaloHalo.getCurrentHaloHaloPrice()
- Update frontend - Harvest button logic
  - frontend should call Rewards.withdrawUnclaimedPoolRewards() and user needs to sign this tx and pay for the gas before redirecting to Vesting page
- Updated site favicon

[HDF-245](https://halodao.atlassian.net/browse/HDF-245)
[HDF-246](https://halodao.atlassian.net/browse/HDF-246)

Also included here:
[HDF-80](https://halodao.atlassian.net/browse/HDF-80) but call on `Rewards.getClaimedPoolRewardsByUserByPool()` is currently commented as it is not yet available for the contract. This task is tracked separately here: https://halodao.atlassian.net/browse/HDF-77

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [x] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Review by tracyarciaga — APPROVED** [review]
Tested, and the vesting modal flow is working as expected. 
Code changes looks good.
Just one minor thing before you @schystz merge:
1. Please rename DSRT to RNBW in the vesting modal.

**Comment by mystbrent** [comment]
I've tried to clone and test in my local but I have this error:
Not sure if this only pertains to my local device

```
./src/utils/index.ts
Attempted import error: 'ethers' does not contain a default export (imported as 'ethers').
```

**Comment by schystz** [comment]
> I've tried to clone and test in my local but I have this error:
> Not sure if this only pertains to my local device
> 
> ```
> ./src/utils/index.ts
> Attempted import error: 'ethers' does not contain a default export (imported as 'ethers').
> ```

@mystbrent can you do a `rm -rf node_modules` and `yarn` to reinstall deps and try again?

**Comment by mystbrent** [comment]
I have opened: https://dev-app-halodao--pr8-features-hdf-77-harv-qamkiizj.web.app
And I see this on the console. 

Not sure if this only pertains to my wallet. I am also in Kovan network.

Screen Shot 2021-05-25 at 6 47 06 PM

**Comment by mystbrent** [comment]
> rm -rf node_modules

Sure will do that :)

**Comment by schystz** [comment]
> I have opened: https://dev-app-halodao--pr8-features-hdf-77-harv-qamkiizj.web.app
> And I see this on the console.
> 
> Not sure if this only pertains to my wallet. I am also in Kovan network.
> 
> Screen Shot 2021-05-25 at 6 47 06 PM

Interesting @mystbrent. A couple of questions here:
- is this always happening for you? (even after browser restart or switching networks back to Kovan)
- is the site still loading correctly? how about the sites features? (e.g. staking, unstaking, claiming)
- do you get these errors on dev.app.halodao.com too?

**Comment by schystz** [comment]
> Tested, and the vesting modal flow is working as expected.
> Code changes looks good.
> Just one minor thing before you @schystz merge:
> 
> 1. Please rename DSRT to RNBW in the vesting modal.

Done. Merged your `hdf-252` branch here as well actually + updated the favicon.

**Comment by mystbrent** [comment]
> > I have opened: https://dev-app-halodao--pr8-features-hdf-77-harv-qamkiizj.web.app
> > And I see this on the console.
> > Not sure if this only pertains to my wallet. I am also in Kovan network.
> > Screen Shot 2021-05-25 at 6 47 06 PM
> 
> Interesting @mystbrent. A couple of questions here:
> 
> * is this always happening for you? (even after browser restart or switching networks back to Kovan)
> * is the site still loading correctly? how about the sites features? (e.g. staking, unstaking, claiming)
> * do you get these errors on dev.app.halodao.com too?

No it happened after I staked BPT tokens.

However after removing the cache and hard reset, the issue seems to be fixed now.

**Comment by mystbrent** [comment]
Screen Shot 2021-05-25 at 9 00 53 PM

This is the result of doing a rm -rf node_modules and yarn to reinstall deps.

I've also used the same version of node stated in the .nvmrc.

**Comment by schystz** [comment]
> Screen Shot 2021-05-25 at 9 00 53 PM
> 
> This is the result of doing a rm -rf node_modules and yarn to reinstall deps.
> 
> I've also used the same version of node stated in the .nvmrc.

@mystbrent it looks like you are missing the .env file, or missing the other env variables from the .env file. You can get it from 1password vault, entry name is: `halodao-interface-dev .env`

**Review by ernestpascual — APPROVED** [review]
lgtm!

**Comment by mystbrent** [comment]
> > Screen Shot 2021-05-25 at 9 00 53 PM
> > This is the result of doing a rm -rf node_modules and yarn to reinstall deps.
> > I've also used the same version of node stated in the .nvmrc.
> 
> @mystbrent it looks like you are missing the .env file, or missing the other env variables from the .env file. You can get it from 1password vault, entry name is: `halodao-interface-dev .env`

Thanks @schystz :)

Checked and everything works as expected.

**Review by mystbrent — APPROVED** [review]

**Pull request merged**
