### PR TITLE
Bug fixes/farm computations

### PR DESCRIPTION
**Pull request by schystz**
## Description of Changes
- Bugfix: total stakeable/staked value stays at $0
- [HDB-2](https://halodao.atlassian.net/browse/HDB-2) Bugfix: show correct staked value at all times
- [HDB-3](https://halodao.atlassian.net/browse/HDB-3) APY computation fix

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [ ] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [x] I have written new tests for your core changes, as applicable
* [x] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by chris247474** [comment]
Looks good @schystz LGTM

**Review by tracyarciaga — APPROVED** [review]

**Comment by mystbrent** [comment]
I can't go thru the testing end to end as I do not have the tokens required but upon checking it is as described in the PR.

Off the roof pool values tho

**Review by mystbrent — APPROVED** [review]
I can't go thru the testing end to end as I do not have the tokens required but upon checking it is as described in the PR.

Off the roof pool values tho

**Review by chris247474 — APPROVED** [review]

**Review by bitcoinbrisbane — APPROVED** [review]
LGTM

**Comment by schystz** [comment]
Thanks guys! Merging this now

**Pull request merged**
