### PR TITLE
Enable XIDR on swap

### PR DESCRIPTION
**Pull request by schystz**
**NOTE:
This PR contains changes from https://github.com/HaloDAO/halodao-interface/pull/126**

## Description of Changes
- Added XIDR to Swap page token list (visible only on mainnet)

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-389)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Review by tracyarciaga — APPROVED** [review]
Approving the changes in the halo-tokenlist.ts, however, please check the screenshot I sent on the other PR.  @schystz

**Comment by schystz** [comment]
> Approving the changes in the halo-tokenlist.ts, however, please check the screenshot I sent on the other PR. @schystz

Thanks @tracyarciaga ! Would you mind to re-approve, it reverted after I assigned the reviewers

For the other concern, pls see https://github.com/HaloDAO/halodao-interface/pull/126#issuecomment-987936595

**Review by tracyarciaga — APPROVED** [review]
Addresses are correct though I cannot test swap in mainnet because of insufficient liquidity.

**Review by mystbrent — APPROVED** [review]
Haven't tried swapping since I do not have balance but otherwise looks good! WP @schystz  👍

**Review by barryhalo — APPROVED** [review]

**Pull request merged**
