### PR TITLE
Features/hdf 164 vesting page feedback

### PR DESCRIPTION
**Pull request by schystz**
## Description of Changes

- [HDF-165](https://halodao.atlassian.net/browse/HDF-165)  Change button titles to "Deposit" & "Claim HALO"
- [HDF-171](https://halodao.atlassian.net/browse/HDF-171)  Add insufficient balance text under deposit & claim button
- [HDF-190](https://halodao.atlassian.net/browse/HDF-190) Reset input field to 0 after the transaction has completed

### Claim HALO

0. Get some HALOHALO tokens
1. Set your allowance for the BPT contract to 0 using etherscan (so we can test approve)
2. On withdraw amount field, enter a value
    - if amount > HALOHALO balance, you should see the "insufficient balance" text below the claim HALO button
    - else, button should be enabled and title changed to "Approve" (requires step 1, otherwise title will remain "Stake")
3. Tap claim HALO button and verify that a white circular loader appears and button becomes disabled
4. After confirming the tx in metamask & getting the confirmation toast, wait for a few sec and verify that:
    - withdraw amount resets to 0
    - claim button becomes disabled again
    - HALOHALO balance deducted with withdraw amount
    - HALO balance incremented with x amount (x = withdraw amount * current HALOHALO:HALO rate, e.g. current rate is 1 HALOHALO: 2 HALO, if user withdraws 1 HALOHALO, user shall get 2 HALO)

Use similar steps above to test deposit function (this time HALO instead of HALOHALO)

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [ ] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by tracyarciaga** [comment]
Changes listed are working fine.

**Review by tracyarciaga — APPROVED** [review]
Approving this. All changes working  correctly.

**Review by ernestpascual — APPROVED** [review]
all good!

**Comment by schystz** [comment]
Thanks @tracyarciaga & @ernestpascual ! Merging this PR now :)

**Pull request merged**
