### PR TITLE
HDB-22 Farm showing incorrect staked value for Halo AMM pools

### PR DESCRIPTION
**Pull request by schystz**
## Description of Changes

Adjustments on getPoolLiquidity() helper for HALO AMM pools

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDB-22)

### Developer Checklist:

* [ ] I have followed the guidelines in our Contributing document
* [ ] This PR has a corresponding JIRA ticket
* [ ] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by schystz** [comment]
A note for reviewers:
The failing circleci check can be fixed by merging this PR first: https://github.com/HaloDAO/halodao-interface/pull/90

**Review by 0xAplki — COMMENTED** [review]
Code looks good, just curious on how to test this properly

**Review by bitcoinbrisbane — APPROVED** [review]

**Comment by tracyarciaga** [comment]
> Code looks good, just curious on how to test this properly

@0xAplki  Need to stake and make sure that the "staked value" displayed are same on all pages (Farm and Pool)
Copy pasting the screenshots from the ticket

image
image

image

image

**Review by tracyarciaga — APPROVED** [review]
Code and Testing - approved.

**Review by 0xAplki — APPROVED** [review]

**Pull request merged**
