### PR TITLE
Features/hdf 301 switch network UI tweak

### PR DESCRIPTION
**Pull request by schystz**
## Description of Changes
- Implement HiFi UI design for Switch Network modal
- Hide switch network UI if not connected to Metamask wallet

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-301)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [x] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Review by tracyarciaga — APPROVED** [review]
All good. Approving this!

**Comment by barryhalo** [comment]
@schystz Looks good to me, just the integration tests

**Comment by schystz** [comment]
I think we can merge this and create a separate Jira ticket for the integration tests failing. I tried to fix it yesterday but have no luck - and the problem is it takes quite some time to troubleshoot, which I would rather spend on more valuable tasks. If you guys agree @tracyarciaga @barryhalo

**Comment by tracyarciaga** [comment]
> I think we can merge this and create a separate Jira ticket for the integration tests failing. I tried to fix it yesterday but have no luck - and the problem is it takes quite some time to troubleshoot, which I would rather spend on more valuable tasks. If you guys agree @tracyarciaga @barryhalo

Agree @schystz

**Review by ernestpascual — APPROVED** [review]
approving and agreeing to fix integration tests on a separate task

**Comment by schystz** [comment]
Thanks @ernestpascual @tracyarciaga , will proceed with merging now!

**Pull request merged**
