### PR TITLE
Add: Goerli & BSC Testnet support

### PR DESCRIPTION
**Pull request by schystz**
Quick changes:

- Added Goerli & BSC Testnet support
- Fix the bug/fatal error encountered when switching networks
- Updated GH workflows to include new env vars (test networks addresses)

### CODE REVIEW

**Review by tracyarciaga — APPROVED** [review]

**Comment by chris247474** [comment]
@schystz i still get the err when running from this commit
image

**Comment by schystz** [comment]
@ctverceles the fix is still on a different branch (`features/hdf-208-unsupported-networks-bug`) and hasn't merged to develop or this branch yet. I'm waiting for Jofo to confirm if we need to change the UI for the empty pools state before I create the PR for that actually.

- Edited - 
Upon taking a 2nd look. It looks like the error above is caused by missing entries in `.env` file. Please get the latest version from 1password.

**Comment by schystz** [comment]
FYI, merged `features/hdf-208-unsupported-networks-bug` to this PR.

Also updated PR description.

**Review by chris247474 — APPROVED** [review]
All working on my end @schystz . 

I tried to add support for the others but found theres a `validateAndParseAddress()` that seems to be checking the contents of an address (whether its a valid contract address?). 
image

As discussed w james, i guess we can keep this PR open just to add in network support as we deploy contracts to them. I also tried adding support for mumbai testnetwork (of matic) but there's no balancer deployed there. so i tried getting some pool addresses off of quickswap, but their fe doesn't seem to connect to mumbai for some reason...

**Comment by schystz** [comment]
FYI @ctverceles , I also updated GH workflow yaml files to include the new env vars added to the project. Otherwise this causes our tests to fail.

**Comment by schystz** [comment]
Merging this PR now so others can also test on [dev.app.halodao.com](https://dev.app.halodao.com) once its auto deployed. 

We'll just create a new PR for adding other test networks.

**Pull request merged**
