### PR TITLE
Features/hdb 1 approving state button

### PR DESCRIPTION
**Pull request by psalm-ov**
## Description of Changes

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDB-1)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### CODE REVIEW

**Comment by schystz** [comment]
Hi @psalm-ov , sorry can you pls explain the solution taken to solve the problem?

From the video recording on Jira, it looks like approval succeeded and the button simply didn't update to "Deposit". Isn't it the case?

**Comment by psalm-ov** [comment]
> Hi @psalm-ov , sorry can you pls explain the solution taken to solve the problem?
> 
> From the video recording on Jira, it looks like approval succeeded and the button simply didn't update to "Deposit". Isn't it the case?

>Okay i'm doing my PR right now.

**Comment by schystz** [comment]
> > Hi @psalm-ov , sorry can you pls explain the solution taken to solve the problem?
> > From the video recording on Jira, it looks like approval succeeded and the button simply didn't update to "Deposit". Isn't it the case?
> 
> > Okay i'm doing my PR right now.

Hi @psalm-ov , pls let me know once this PR is finalized. Wanted to discuss the solution taken to solve the original problem (HDB-1)

**Comment by psalm-ov** [comment]
> > > Hi @psalm-ov , sorry can you pls explain the solution taken to solve the problem?
> > > From the video recording on Jira, it looks like approval succeeded and the button simply didn't update to "Deposit". Isn't it the case?
> > 
> > 
> > > Okay i'm doing my PR right now.
> 
> Hi @psalm-ov , pls let me know once this PR is finalized. Wanted to discuss the solution taken to solve the original problem (HDB-1)

@schystz, This PR is finalized.

**Review by tracyarciaga — APPROVED** [review]

**Comment by schystz** [comment]
As discussed with @psalm-ov , remaining to do here is to merge the `features/hdev-264-ui-for-handling-errors` to this branch so it can reuse the generic modal components for displaying the errors, instead of introducing a new error modal component on this branch.

**Comment by psalm-ov** [comment]
> As discussed with @psalm-ov , remaining to do here is to merge the `features/hdev-264-ui-for-handling-errors` to this branch so it can reuse the generic modal components for displaying the errors, instead of introducing a new error modal component on this branch.

@schystz , We will discussed this with our today's meeting

**Comment by psalm-ov** [comment]
> > As discussed with @psalm-ov , remaining to do here is to merge the `features/hdev-264-ui-for-handling-errors` to this branch so it can reuse the generic modal components for displaying the errors, instead of introducing a new error modal component on this branch.
> 
> @schystz , We will discuss this with our today's meeting

**Comment by schystz** [comment]
@psalm-ov I suggest closing this PR since the original HDB-1 ticket has been resolved already.

I moved the remaining work here into a new ticket, pls see https://halodao.atlassian.net/browse/HDB-68

**Comment by psalm-ov** [comment]
> @psalm-ov I suggest closing this PR since the original HDB-1 ticket has been resolved already.
> 
> I moved the remaining work here into a new ticket, pls see https://halodao.atlassian.net/browse/HDB-68

Yeah, Done reviewing the ticket.

**Comment by schystz** [comment]
Closing this PR in favor of https://github.com/HaloDAO/halodao-interface/pull/157

**Pull request closed without merging**
